In [1]:
import numpy as np
a = np.array([[-0.57098887, -0.4274751 , -0.38459931, -0.58593526],
         [-0.22279713, -0.51723555,  0.82462029,  0.05319973],
         [ 0.67492385, -0.69294472, -0.2531966 ,  0.01403201],
         [ 0.41086611,  0.26374238,  0.32859738, -0.80848795]])

In [2]:
print(a)

[[-0.57098887 -0.4274751  -0.38459931 -0.58593526]
 [-0.22279713 -0.51723555  0.82462029  0.05319973]
 [ 0.67492385 -0.69294472 -0.2531966   0.01403201]
 [ 0.41086611  0.26374238  0.32859738 -0.80848795]]


In [3]:
print(a[:,:2])

[[-0.57098887 -0.4274751 ]
 [-0.22279713 -0.51723555]
 [ 0.67492385 -0.69294472]
 [ 0.41086611  0.26374238]]


In [4]:
print(np.argsort(a, axis=1))

[[3 0 1 2]
 [1 0 3 2]
 [1 2 3 0]
 [3 1 2 0]]
